# Generated by Django 4.1.7 on 2023-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('no_of_sub', models.IntegerField()),
                ('cid', models.IntegerField()),
            ],
        ),
    ]
