# Generated by Django 4.1.7 on 2023-02-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_show_show'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
