# Generated by Django 4.1.7 on 2023-03-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='no_of_sub',
            field=models.IntegerField(default=0),
        ),
    ]
