# Generated by Django 4.1.7 on 2023-07-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_pic',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='catid',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_price',
        ),
    ]
