# Generated by Django 4.1.7 on 2023-11-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_rename_item_name_item_name_rename_item_pic_item_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pic_name',
            field=models.TextField(default='okay'),
            preserve_default=False,
        ),
    ]
