# Generated by Django 4.1.7 on 2023-02-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.IntegerField()),
                ('item_pic', models.ImageField(upload_to='')),
                ('catid', models.IntegerField()),
            ],
        ),
    ]
