# Generated by Django 4.1.7 on 2023-03-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcat',
            name='subcatid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
