# Generated by Django 4.1.7 on 2023-03-01 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sub_cat', '0002_subcat_subcatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcat',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
