# Generated by Django 4.1.7 on 2023-03-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_cat', '0003_subcat_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcat',
            name='subcatid',
        ),
    ]
