# Generated by Django 4.1.7 on 2023-07-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_cat', '0004_remove_subcat_subcatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcat',
            name='self_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
