# Generated by Django 4.1.7 on 2023-07-14 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_cat', '0005_subcat_self_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcat',
            name='self_id',
        ),
    ]
